
package chungtoi.client.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChungToi", targetNamespace = "http://server.chungtoi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChungToi {


    /**
     * 
     * @param playerOneId
     * @param playerTwoName
     * @param playerTwoId
     * @param playerOneName
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preRegistro", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PreRegistro")
    @ResponseWrapper(localName = "preRegistroResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PreRegistroResponse")
    @Action(input = "http://server.chungtoi/ChungToi/preRegistroRequest", output = "http://server.chungtoi/ChungToi/preRegistroResponse")
    public int preRegistro(
        @WebParam(name = "playerOneName", targetNamespace = "")
        String playerOneName,
        @WebParam(name = "playerOneId", targetNamespace = "")
        int playerOneId,
        @WebParam(name = "playerTwoName", targetNamespace = "")
        String playerTwoName,
        @WebParam(name = "playerTwoId", targetNamespace = "")
        int playerTwoId);

    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraJogador", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.RegistraJogador")
    @ResponseWrapper(localName = "registraJogadorResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.RegistraJogadorResponse")
    @Action(input = "http://server.chungtoi/ChungToi/registraJogadorRequest", output = "http://server.chungtoi/ChungToi/registraJogadorResponse")
    public int registraJogador(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encerraPartida", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EncerraPartida")
    @ResponseWrapper(localName = "encerraPartidaResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EncerraPartidaResponse")
    @Action(input = "http://server.chungtoi/ChungToi/encerraPartidaRequest", output = "http://server.chungtoi/ChungToi/encerraPartidaResponse")
    public int encerraPartida(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "temPartida", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.TemPartida")
    @ResponseWrapper(localName = "temPartidaResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.TemPartidaResponse")
    @Action(input = "http://server.chungtoi/ChungToi/temPartidaRequest", output = "http://server.chungtoi/ChungToi/temPartidaResponse")
    public int temPartida(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ehMinhaVez", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EhMinhaVez")
    @ResponseWrapper(localName = "ehMinhaVezResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EhMinhaVezResponse")
    @Action(input = "http://server.chungtoi/ChungToi/ehMinhaVezRequest", output = "http://server.chungtoi/ChungToi/ehMinhaVezResponse")
    public int ehMinhaVez(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtemTabuleiro", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.ObtemTabuleiro")
    @ResponseWrapper(localName = "obtemTabuleiroResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.ObtemTabuleiroResponse")
    @Action(input = "http://server.chungtoi/ChungToi/obtemTabuleiroRequest", output = "http://server.chungtoi/ChungToi/obtemTabuleiroResponse")
    public String obtemTabuleiro(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param orientation
     * @param position
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "posicionaPeca", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PosicionaPeca")
    @ResponseWrapper(localName = "posicionaPecaResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PosicionaPecaResponse")
    @Action(input = "http://server.chungtoi/ChungToi/posicionaPecaRequest", output = "http://server.chungtoi/ChungToi/posicionaPecaResponse")
    public int posicionaPeca(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "position", targetNamespace = "")
        int position,
        @WebParam(name = "orientation", targetNamespace = "")
        int orientation);

    /**
     * 
     * @param currentPosition
     * @param userId
     * @param movement
     * @param newOrientation
     * @param direction
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "movePeca", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.MovePeca")
    @ResponseWrapper(localName = "movePecaResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.MovePecaResponse")
    @Action(input = "http://server.chungtoi/ChungToi/movePecaRequest", output = "http://server.chungtoi/ChungToi/movePecaResponse")
    public int movePeca(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "currentPosition", targetNamespace = "")
        int currentPosition,
        @WebParam(name = "direction", targetNamespace = "")
        int direction,
        @WebParam(name = "movement", targetNamespace = "")
        int movement,
        @WebParam(name = "newOrientation", targetNamespace = "")
        int newOrientation);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtemOponente", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.ObtemOponente")
    @ResponseWrapper(localName = "obtemOponenteResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.ObtemOponenteResponse")
    @Action(input = "http://server.chungtoi/ChungToi/obtemOponenteRequest", output = "http://server.chungtoi/ChungToi/obtemOponenteResponse")
    public String obtemOponente(
        @WebParam(name = "name", targetNamespace = "")
        int name);

}
