
package chungtoi.client.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChungToi", targetNamespace = "http://server.chungtoi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChungToi {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOpponent", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.GetOpponent")
    @ResponseWrapper(localName = "getOpponentResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.GetOpponentResponse")
    @Action(input = "http://server.chungtoi/ChungToi/getOpponentRequest", output = "http://server.chungtoi/ChungToi/getOpponentResponse")
    public String getOpponent(
        @WebParam(name = "name", targetNamespace = "")
        int name);

    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignup", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PlayerSignup")
    @ResponseWrapper(localName = "playerSignupResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PlayerSignupResponse")
    @Action(input = "http://server.chungtoi/ChungToi/playerSignupRequest", output = "http://server.chungtoi/ChungToi/playerSignupResponse")
    public int playerSignup(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endMatch", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EndMatch")
    @ResponseWrapper(localName = "endMatchResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.EndMatchResponse")
    @Action(input = "http://server.chungtoi/ChungToi/endMatchRequest", output = "http://server.chungtoi/ChungToi/endMatchResponse")
    public int endMatch(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "haveMatch", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.HaveMatch")
    @ResponseWrapper(localName = "haveMatchResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.HaveMatchResponse")
    @Action(input = "http://server.chungtoi/ChungToi/haveMatchRequest", output = "http://server.chungtoi/ChungToi/haveMatchResponse")
    public int haveMatch(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isMyTurn", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.IsMyTurn")
    @ResponseWrapper(localName = "isMyTurnResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.IsMyTurnResponse")
    @Action(input = "http://server.chungtoi/ChungToi/isMyTurnRequest", output = "http://server.chungtoi/ChungToi/isMyTurnResponse")
    public int isMyTurn(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBoard", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.GetBoard")
    @ResponseWrapper(localName = "getBoardResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.GetBoardResponse")
    @Action(input = "http://server.chungtoi/ChungToi/getBoardRequest", output = "http://server.chungtoi/ChungToi/getBoardResponse")
    public String getBoard(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param orientation
     * @param position
     * @param userId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "placePiece", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PlacePiece")
    @ResponseWrapper(localName = "placePieceResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.PlacePieceResponse")
    @Action(input = "http://server.chungtoi/ChungToi/placePieceRequest", output = "http://server.chungtoi/ChungToi/placePieceResponse")
    public int placePiece(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "position", targetNamespace = "")
        int position,
        @WebParam(name = "orientation", targetNamespace = "")
        int orientation);

    /**
     * 
     * @param currentPosition
     * @param userId
     * @param movement
     * @param newOrientation
     * @param direction
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "movePiece", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.MovePiece")
    @ResponseWrapper(localName = "movePieceResponse", targetNamespace = "http://server.chungtoi/", className = "chungtoi.client.proxy.MovePieceResponse")
    @Action(input = "http://server.chungtoi/ChungToi/movePieceRequest", output = "http://server.chungtoi/ChungToi/movePieceResponse")
    public int movePiece(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "currentPosition", targetNamespace = "")
        int currentPosition,
        @WebParam(name = "direction", targetNamespace = "")
        int direction,
        @WebParam(name = "movement", targetNamespace = "")
        int movement,
        @WebParam(name = "newOrientation", targetNamespace = "")
        int newOrientation);

}
